name: "Release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Compile PDF
        run: ./compile.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: "*.pdf"
          fail_on_unmatched_files: true
